### PR TITLE
Improve radar CPU usage

### PR DESCRIPTION
**Pull request by gwww**
I started on this path looking for the memory leak and ended up with greatly improved speed. I think the major speed improvement comes from caching the composed radar images instead of composing them each time a GIF is needed.

In my tests it takes about half the time to create a GIF now.

As I said I started on this path after spending close to a day looking for the memory leak, which I'm convinced exists and mostly convinced that the leak is inside of the Pillow library. Here is one of the tests I've been using to find the memory leak:

```
import asyncio
import os
import psutil
from datetime import datetime

from env_canada import ECRadar


pid = os.getpid()
process = psutil.Process(pid)

radar_coords = ECRadar(coordinates=(45.41117000, -75.69812000))
radar_coords.precip_type = "auto"
while 1:
    animated_gif = asyncio.run(radar_coords.get_loop())
    print(
        f"{datetime.now().strftime("%H:%M:%S.%f")} {process.memory_info().rss / 1000000} MB"
    )
```

Since composed images are cached every call to `get_loop()` after the first call (which is building up the cache) basically just builds the GIF from the set of cached images, so I'm guessing the leak is in the Pillow GIF building code.

### CODE REVIEW

**Comment by gwww** [comment]
The flake8 error seems bogus unless I've gone crazy.

**Comment by gwww** [comment]
I put this as draft as still pondering and reviewing myself. I've tested quite a lot and it has worked wonderfully. Would like to hear your opinion.

**Comment by michaeldavie** [comment]
Nice! I'll take a look.

It looks like `flake8` is confused by the inner `"` characters: 

```python
timestamp = f"{timestamp_label[self.layer_key][self.language]} @ {frame_time.astimezone().strftime('%H:%M')}"
```

**Comment by gwww** [comment]
FYI I think I found a work around for the leak. Usiothe Image lib instead of imageio. I’ll try to push that change tonight. 

I’ll be offline for a couple of days after tonight.

**Comment by gwww** [comment]
Tests are failing. Will look at them soon unless you get there first :)

**Comment by gwww** [comment]
I just did some profiling, comparing the old code (with memory leak) to the new code. This is the script that I ran:
```
import asyncio
import os
import psutil
import time
from datetime import datetime, timedelta
from env_canada import ECRadar

pid = os.getpid()
process = psutil.Process(pid)
radar_coords = ECRadar(coordinates=(45.41117000, -75.69812000))
radar_coords.precip_type = "rain"

i = 1
end_time = datetime.now() + timedelta(minutes=30)
while end_time > datetime.now():
    animated_gif = asyncio.run(radar_coords.get_loop())
    # open("radar-rain.gif", "wb").write(animated_gif)

    mem_str = f"{process.memory_info().rss / 1000000:>8.2f} MB"
    cpu_str = time.process_time()
    print(f"{i:>4} {datetime.now().strftime("%H:%M:%S")} {mem_str} {cpu_str:>6.2f} CPU")
    i = i + 1
```
Both old and new ran for 30 minutes. Caching of files retrieved remotely seemed similar in both old and new - very low load on the Environment Canada servers! Average memory per GIF is probably not important because it's a memory leak situation for the old code - but I put it here anyhow. What is great is that the generation of a GIF takes ~ 1/3 the time, and of course, its believed there is no memory leak. Memory seems fairly stable in the new code.

| 30 minutes each         | Old code        | New code        |
| ------------------ | --------------- | --------------- |
| GIFs generated     | 586             | 2638            |
| Memory at end      | 4028.89 MB      | 1056.03 MB      |
| Avg memory per GIF | 6.88 MB         | 0.40 MB         |
| CPU at end         | 1076.29 seconds | 1794.56 seconds |
| Avg CPU per GIF    | 1.83 seconds    | 0.68 seconds    |
| GIF size           | 1.0 MB          | 1.0 MB          |

**Comment by michaeldavie** [comment]
Awesome, thanks for all your work on this!

**Pull request merged**
