### PR TITLE
Cache weather site list. Add debug logs.

### PR DESCRIPTION
**Pull request by gwww**
Fixed one bug. Add logs for easier debugging. May need more logs, but have a good start.

### CODE REVIEW

**Comment by michaeldavie** [comment]
Let me know if you'd like me to make a release here.

**Comment by gwww** [comment]
I think you can go ahead and make a release. The change I've made to the integration is switch the warning to an info log for AQHI and set `self._attr_entity_registry_enabled_default` to False for AQHI - which will only affect people adding the integration (as opposed to those who have it enabled).

These debug logs will help a lot. They are only on weather and AQHI so far. I did not do anything for radar.

Do you have any idea why the Quebec AQHI doesn't have any info? Is that new? Is there another source?

**Comment by alexandreleroux** [comment]
> Do you have any idea why the Quebec AQHI doesn't have any info? Is that new? Is there another source?

@gwww please see [the official documentation](https://eccc-msc.github.io/open-data/msc-data/aqhi/readme_aqhi-datamartjson_en/): _"Quebec did not agree to the publication of current air quality in the form of an air quality health index (AQHI). This explains why no observation are available at the address: [http://hpfx.collab.science.gc.ca/YYYMMDD/WXO-DD/air_quality/aqhi/que/observation/realtime/json](http://hpfx.collab.science.gc.ca/). However, the Ministère du Développement durable, Environnement et Lutte contre les changements climatiques (MDDELCC) and Ville de Montreal also redistribute some of their data on [the American AirNow portal](https://www.epa.gov/outdoor-air-quality-data/download-daily-data)."_

Hope this helps. Furthermore, AQHI observations and forecast data is now available from the OCG API - Features standard (since last week!). Example here: https://api.weather.gc.ca/collections/aqhi-observations-realtime/items?limit=100&startindex=0&sortby=observation_datetime_text_fr

**Comment by gwww** [comment]
I think we were typing at the same time. I just discovered that text and added it to the HA bug!

**Comment by michaeldavie** [comment]
I've added release v0.5.21. I also made a tweak so that the missing AQHI observation won't result in an unhandled exception but will return `None`. I think this should make the forecast values available to HA when a Quebec site is selected.

**Pull request merged**
